let plants=[
    "巨獸鹿角蕨",
    "女王鹿角蕨",
    "蝴蝶鹿角蕨",
    "何其美鹿角蕨",
    "亞洲猴腦鹿角蕨",
    "圓盾鹿角蕨",
    "皇冠鹿角蕨",
    "安地斯鹿角蕨",
    "象耳鹿角蕨",
    "非洲猴腦鹿角蕨",
    "二叉鹿角蕨",
    "三角鹿角蕨",
    "立葉鹿角蕨",
    "爪哇鹿角蕨",
    "深綠鹿角蕨",
    "愛麗絲鹿角蕨"
]

let pictures=[
    "random-selector/image/img1.jpg",
    "random-selector/image/img2.jpg",
    "random-selector/image/img3.jpg",
    "random-selector/image/img4.jpg",
    "random-selector/image/img5.jpg",
    "random-selector/image/img6.jpg",
    "random-selector/image/img7.jpg",
    "random-selector/image/img8.jpg",
    "random-selector/image/img9.jpg",
    "random-selector/image/img10.jpg",
    "random-selector/image/img11.jpg",
    "random-selector/image/img12.jpg",
    "random-selector/image/img13.jpg",
    "random-selector/image/img14.jpg",
    "random-selector/image/img15.jpg",
    "random-selector/image/img1.jpg"
];

let characteristic=[
    "大型鹿角蕨，孢子上有四個分支，兩個左右凹陷處各有一個包子生長點",
    "靠近芽點處的營養液會有鋸齒狀邊緣，是體型最大的鹿角蕨，孢子葉第一個分裂成上下兩個型態，上部無分裂，下半部左右兩側再長出下垂如裙擺的葉子，年輕的植株不太容易長出孢子葉",
    "在冬季的時候會休眠，休眠期孢子葉會捲曲減少水分散失，平常喜歡多水，但休眠期保持稍微有點濕度就可以，孢子葉型態較其他大型種比起來中段根末段都較寬，有如蝴蝶翅膀般",
    "孢子葉跟營養液的比例較對稱，孢子葉生長與女王相似，孢子葉第一個分裂成上下兩個型態，但上下都會長出分裂",
    "與蟻共生的鹿角蕨，營養葉上具有腦狀的紋路，提供螞蟻作為通道，孢子向上生長如珊瑚狀，孢子盤如湯匙，獨立生長在第一個分岔中間，是容易被昆蟲啃食的鹿角蕨",
    "營養葉無分裂會整個覆蓋根部包成圓形，孢子葉向上生長",
    "營養葉高冠有分裂，太多營養葉水溶液水傷，孢子葉分為上方的短葉根下方的長葉，孢子盤位於中間呈現勺子狀",
    "唯一在美洲大陸的鹿角蕨品種，孢子葉可達2公尺長，葉片上覆蓋許多白毛",
    "唯一孢子葉部分裂的品種，孢子葉片如象耳，葉脈紋路明顯，營養葉高呈現波浪狀",
    "與蟻共生的鹿角蕨，營養葉上具有腦狀的紋路，提供螞蟻作為通道，營養葉不裂葉，孢子葉短小，是最小型的鹿角蕨，夏天照顧難度較高，以及容易被昆蟲啃食",
    "市場上最常見的品種，適應力強，好照顧，營養葉淺裂",
    "容易生側芽，孢子葉末端淺淺的分叉，看上去有點像多邊形，營養葉高呈現波浪狀",
    "分為銀葉/綠葉品種，孢子葉直立向上生長，營養葉呈現較深的鋸齒狀",
    "營養葉高具有深裂，孢子葉很長是他的特色",
    "孢子葉寬大，顏色偏深綠色，營養葉無分裂",
    "孢子葉呈現象魚尾狀，容易出現黑斑點，營養葉包起成圓盾狀",
]